// Generates seed.sql from questions.js so the database and the site always match.
// Usage: node build-seed.js
const fs = require('fs');
const vm = require('vm');
const path = require('path');

const ctx = { window: {} };
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname, 'questions.js'), 'utf8'), ctx);
const Q = ctx.window.QUESTIONS;

const sq = s => "'" + String(s).replace(/'/g, "''") + "'";
const rows = Q.map(q =>
  `(${q.id}, ${sq(q.topic)}, ${sq(q.difficulty)}, ${sq(q.question)}, ${sq(JSON.stringify(q.choices))}::jsonb, ${q.answer}, ${sq(q.solution)}, ${q.points})`
);

const sql =
`-- Generated by build-seed.js. Safe to re-run: existing ids are updated.
insert into public.questions (id, topic, difficulty, question, choices, answer_index, solution, points) values
${rows.join(',\n')}
on conflict (id) do update set
  topic = excluded.topic, difficulty = excluded.difficulty, question = excluded.question,
  choices = excluded.choices, answer_index = excluded.answer_index,
  solution = excluded.solution, points = excluded.points;
`;
fs.writeFileSync(path.join(__dirname, 'seed.sql'), sql);
console.log(`seed.sql written with ${Q.length} questions`);
