-- Generated by build-seed.js. Safe to re-run: existing ids are updated.
insert into public.questions (id, topic, difficulty, question, choices, answer_index, solution, points) values
(1, 'DC Circuits', 'easy', 'Three resistors of 6 Ω, 12 Ω and 4 Ω are connected in parallel. What is the equivalent resistance?', '["1 Ω","2 Ω","4 Ω","22 Ω"]'::jsonb, 1, '1/Req = 1/6 + 1/12 + 1/4
1/Req = 2/12 + 1/12 + 3/12 = 6/12
Req = 12/6 = 2 Ω', 10),
(2, 'DC Circuits', 'easy', 'A 12 V source is connected to a 4 Ω and an 8 Ω resistor in series. What is the voltage across the 8 Ω resistor?', '["4 V","6 V","8 V","12 V"]'::jsonb, 2, 'Rt = 4 + 8 = 12 Ω
I = V/Rt = 12/12 = 1 A
V(8 Ω) = I × R = 1 × 8 = 8 V', 10),
(3, 'DC Circuits', 'medium', 'A heater rated 1500 W at 120 V is operating at its rating. What is its resistance?', '["8.0 Ω","9.6 Ω","12.5 Ω","18.0 Ω"]'::jsonb, 1, 'P = V²/R
R = V²/P = 120² / 1500 = 14,400 / 1500 = 9.6 Ω', 15),
(4, 'AC Circuits', 'medium', 'A series RL circuit has R = 30 Ω and XL = 40 Ω and is connected to a 120 V source. Find the current.', '["1.7 A","2.4 A","3.0 A","4.0 A"]'::jsonb, 1, 'Z = √(R² + XL²) = √(30² + 40²) = √2500 = 50 Ω
I = V/Z = 120/50 = 2.4 A', 15),
(5, 'AC Circuits', 'medium', 'For the same series RL circuit (R = 30 Ω, XL = 40 Ω, 120 V), what is the real power consumed?', '["288 W","172.8 W","230.4 W","120 W"]'::jsonb, 1, 'I = 120/50 = 2.4 A
Real power is dissipated only in R:
P = I²R = (2.4)² × 30 = 5.76 × 30 = 172.8 W
(Check: S = VI = 288 VA, pf = R/Z = 0.6, P = 288 × 0.6 = 172.8 W)', 15),
(6, 'AC Circuits', 'hard', 'A series RLC circuit has L = 10 mH and C = 10 µF. What is its resonant frequency?', '["159 Hz","503 Hz","1007 Hz","3162 Hz"]'::jsonb, 1, 'fr = 1 / (2π√(LC))
LC = (10×10⁻³)(10×10⁻⁶) = 1×10⁻⁷
√(LC) = 3.162×10⁻⁴
fr = 1 / (2π × 3.162×10⁻⁴) = 1 / 1.987×10⁻³ ≈ 503 Hz', 20),
(7, 'Electrostatics', 'easy', 'Two point charges of 2 µC each are placed 0.3 m apart in air. What is the force between them? (k = 9×10⁹ N·m²/C²)', '["0.12 N","0.4 N","1.2 N","4.0 N"]'::jsonb, 1, 'F = k q1 q2 / r²
F = (9×10⁹)(2×10⁻⁶)(2×10⁻⁶) / (0.3)²
F = 0.036 / 0.09 = 0.4 N (repulsive)', 10),
(8, 'Electrostatics', 'easy', 'A 10 µF and a 20 µF capacitor are connected in series. What is the equivalent capacitance?', '["30 µF","15 µF","6.67 µF","5 µF"]'::jsonb, 2, 'Series capacitors: Ceq = (C1 × C2)/(C1 + C2)
Ceq = (10 × 20)/(10 + 20) = 200/30 = 6.67 µF', 10),
(9, 'Electrostatics', 'medium', 'How much energy is stored in a 100 µF capacitor charged to 200 V?', '["0.02 J","1 J","2 J","4 J"]'::jsonb, 2, 'W = ½ C V²
W = ½ (100×10⁻⁶)(200)² = ½ (100×10⁻⁶)(40,000) = 2 J', 15),
(10, 'Electromagnetic Induction', 'medium', 'A coil of 200 turns is linked by a flux that changes uniformly from 0.05 Wb to 0.01 Wb in 0.2 s. What is the average induced emf?', '["8 V","10 V","40 V","200 V"]'::jsonb, 2, 'e = N (ΔΦ/Δt)
ΔΦ = 0.05 − 0.01 = 0.04 Wb
e = 200 × (0.04 / 0.2) = 200 × 0.2 = 40 V', 15),
(11, 'Magnetic Circuits', 'easy', 'A coil of 500 turns carries 2 A around a magnetic path 0.4 m long. What is the magnetic field intensity H?', '["1000 AT/m","1250 AT/m","2500 AT/m","5000 AT/m"]'::jsonb, 2, 'mmf = NI = 500 × 2 = 1000 ampere-turns
H = mmf / l = 1000 / 0.4 = 2500 AT/m', 10),
(12, 'Instrumentation', 'medium', 'A d''Arsonval movement has a full-scale current of 50 µA. If it is used as a 100 V voltmeter, what is the total resistance of the meter (movement + multiplier)?', '["20 kΩ","200 kΩ","2 MΩ","20 MΩ"]'::jsonb, 2, 'Total resistance = Vfs / Ifs
= 100 / (50×10⁻⁶) = 2×10⁶ Ω = 2 MΩ
(Sensitivity = 1/Ifs = 20,000 Ω/V; 20,000 × 100 V = 2 MΩ)', 15),
(13, 'DC Generators', 'medium', 'A shunt generator delivers 100 A to the load at 230 V terminal voltage. The field current is 5 A and the armature resistance is 0.1 Ω. Find the generated emf (neglect brush drop).', '["230.0 V","240.0 V","240.5 V","241.0 V"]'::jsonb, 2, 'Ia = IL + If = 100 + 5 = 105 A
Eg = Vt + Ia·Ra = 230 + (105)(0.1) = 230 + 10.5 = 240.5 V', 15),
(14, 'DC Motors', 'medium', 'A shunt motor is connected to a 230 V supply and draws an armature current of 40 A. If Ra = 0.5 Ω, what is the mechanical power developed by the armature?', '["8.4 kW","9.2 kW","8.0 kW","20 kW"]'::jsonb, 0, 'Back emf Eb = V − Ia·Ra = 230 − (40)(0.5) = 210 V
Pd = Eb × Ia = 210 × 40 = 8400 W = 8.4 kW
(9.2 kW is the electrical input to the armature, V × Ia)', 15),
(15, 'Alternators', 'easy', 'An 8-pole alternator generates 60 Hz. What is its synchronous speed?', '["600 rpm","900 rpm","1200 rpm","1800 rpm"]'::jsonb, 1, 'Ns = 120 f / P
Ns = 120 × 60 / 8 = 7200 / 8 = 900 rpm', 10),
(16, 'Transformers', 'medium', 'A 50 kVA, 2400/240 V single-phase transformer. What is the rated secondary current?', '["20.8 A","104.2 A","208.3 A","2083 A"]'::jsonb, 2, 'I2 = kVA × 1000 / V2 = 50,000 / 240 = 208.3 A
(The primary current is 50,000/2400 = 20.8 A)', 15),
(17, 'Transformers', 'hard', 'A 10 kVA transformer has a core loss of 100 W and a copper loss of 150 W at full load. What is the full-load efficiency at unity power factor?', '["95.0%","96.6%","97.6%","98.5%"]'::jsonb, 2, 'Output = 10 kVA × 1.0 = 10,000 W
Total losses = 100 + 150 = 250 W
Input = 10,000 + 250 = 10,250 W
η = 10,000 / 10,250 = 0.9756 = 97.6%', 20),
(18, 'Induction Motors', 'medium', 'A 6-pole, 60 Hz induction motor runs at 1140 rpm. What is the slip?', '["3%","4%","5%","6%"]'::jsonb, 2, 'Ns = 120 f / P = 120 × 60 / 6 = 1200 rpm
s = (Ns − N)/Ns = (1200 − 1140)/1200 = 60/1200 = 0.05 = 5%', 15),
(19, 'Synchronous Motors', 'easy', 'Which statement about an over-excited synchronous motor is correct?', '["It operates at a lagging power factor","It operates at a leading power factor and can be used to correct the power factor of a system","It runs below synchronous speed","It cannot be started without a load"]'::jsonb, 1, 'When the field is over-excited, the motor''s back emf is large and the armature draws a leading current, so it acts like a capacitor to the supply. That is why synchronous condensers are used for power factor correction. A synchronous motor always runs at exactly synchronous speed.', 10),
(20, 'Transmission Lines', 'medium', 'The receiving-end voltage of a line is 13.2 kV at no load and 12 kV at full load. What is the voltage regulation?', '["9.1%","10%","11%","1.2%"]'::jsonb, 1, 'VR = (VNL − VFL)/VFL × 100
VR = (13.2 − 12)/12 × 100 = 1.2/12 × 100 = 10%
(Dividing by the no-load voltage would wrongly give 9.1%.)', 15),
(21, 'Faults', 'hard', 'A generator rated 10 MVA has a total fault impedance of 0.2 per unit on its own base. What is the three-phase short-circuit MVA?', '["2 MVA","10 MVA","50 MVA","200 MVA"]'::jsonb, 2, 'Fault current (pu) = 1 / Zpu = 1 / 0.2 = 5 pu
Short-circuit MVA = MVAbase × Ipu = 10 × 5 = 50 MVA
(or MVAsc = MVAbase / Zpu = 10/0.2 = 50 MVA)', 20),
(22, 'Illumination', 'easy', 'A point source of 1000 cd hangs 4 m directly above a table. What is the illuminance on the table directly below it?', '["62.5 lux","250 lux","1000 lux","15.6 lux"]'::jsonb, 0, 'Inverse-square law: E = I / d²
E = 1000 / 4² = 1000 / 16 = 62.5 lux', 10),
(23, 'Rectifiers & Converters', 'medium', 'A single-phase full-wave rectifier has a peak output voltage Vm = 170 V. What is the average (dc) output voltage?', '["54.1 V","108.2 V","120.2 V","170 V"]'::jsonb, 1, 'For a full-wave rectifier: Vdc = 2 Vm / π
Vdc = 2 × 170 / 3.1416 = 340 / 3.1416 ≈ 108.2 V
(A half-wave rectifier would give Vm/π = 54.1 V.)', 15),
(24, 'Power Plants', 'hard', 'A hydroelectric plant has a net head of 50 m and a flow of 10 m³/s. If the overall efficiency is 80%, what is the electrical output?', '["3.14 MW","3.92 MW","4.91 MW","39.2 MW"]'::jsonb, 1, 'P = ρ g Q H η
P = (1000)(9.81)(10)(50)(0.80)
P = 4,905,000 × 0.80 = 3,924,000 W ≈ 3.92 MW', 20),
(25, 'Power Plants', 'medium', 'A 100 MW plant generates 438,000 MWh in a year (8760 hours). What is its capacity factor?', '["25%","50%","75%","100%"]'::jsonb, 1, 'Maximum possible energy = 100 MW × 8760 h = 876,000 MWh
Capacity factor = actual / maximum = 438,000 / 876,000 = 0.50 = 50%', 15)
on conflict (id) do update set
  topic = excluded.topic, difficulty = excluded.difficulty, question = excluded.question,
  choices = excluded.choices, answer_index = excluded.answer_index,
  solution = excluded.solution, points = excluded.points;
